### ISSUE TITLE
Comments/Questions from Chris Oakden

### ISSUE THREAD

**Issue by coakden** [jvcasillas/datasci_assignments#75]
Comments:
The information is presented clearly, and the organization is effective. I like the fact that you place the hypotheses and conclusion in the same slide (slide 4), so the anticipated and actual outcomes of the experiment are in the same place. I agree with your assessment about the use of t-tests in the authors' statistical analysis. The alternative analysis you propose in slide 6 was well thought-out and motivated by the specifics of the authors' experiment.

Question:
I had a question about which t-tests the authors performed. So, there were three contexts (phrase-medial, phrase-final, and utterance-final); did the authors perform pairwise t-tests for each combination of the two? If the conclusion was that duration increased by the size of the prosodic unit, was it the case that vowels in the utterance-final context were longer than the phrase-final context? Were both longer than in the phrase-medial context?

**Comment by jvcasillas** [comment]
Hey @coakden could you move this to the repo of author of the presentation (or @ them here)?

**Comment by coakden** [comment]
sorry about that! i got a little confused. should i just delete this thread?

**Comment by jvcasillas** [comment]
Sure. That’s fine.
