### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dinemamadou** [jvcasillas/datasci_assignments#76]
Overall, the presentation is comprehensible and provides the finding of the paper at the onset of slides (S 2). However, it lacks details about the participants, their number and the type of t-tests (dependent vs independent) that were run. These details are important to accurately interpret the validity of their results and help us see whether or not there are other test-related problems to worry about. Additionally, it would have been helpful to comment on the researchers' equation of statistical significance to theoretical significance. You only reported that they equated the two without stating that in fact, statistical significance alone does not mean what they said it meant. Other than these points, the other comments you made are accurate and need to be taken seriously by the authors. Good job!

**Comment by jvcasillas** [comment]
@dinemamadou could you move this comment to the repo of the author?
