### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dinemamadou** [jvcasillas/datasci_assignments#77]
Overall the presentation has expository merits and elaborates where appropriate. Also, the organization of the presentation in two main parts (summary of the paper and comments) make it easy to follow. If anything, the first point under "Novelty of Analysis > B" (slide 7) seems not to be too appropriate for that part. That is, although calculating the f0 moment using the f0 velocity is something you haven't seen before, it is not a novelty of analysis in the statistical sense and should not be mention in this part. Additionally, the discrepancy between the Alfa values (S 8) is not necessarily a problem, in my opinion, because different experiments/tests may require different alpha levels. There would be a problem, however, if their alpha levels were not motivated each time they're used. Your comments on the contradiction of their conclusion with their hypothesis seem right because the main effect of different targets shows that there are systematic variations, which supports the idea that targets are unspecific in the phonetic module. In a nutshell, your comments are insightful and did not miss the bigger picture view. So, good job!

**Comment by jvcasillas** [comment]
@dinemamadou same here.
